version: 0.3.2.{build}
image: Visual Studio 2019
configuration: Release
environment:
  semantic_version: '0.3.2'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(semantic_version)
  file_version: '{version}'

install:
  - dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal

deploy:
  - provider: NuGet
    api_key:
      secure: SBoWmhdeizdgzq8iC+rRWP/UqrfjczKbwbPFCu/udNJydSGSRvPT6H5oxUtF2s+V
    on:
      APPVEYOR_REPO_TAG: true
