version: 0.1.0.{build}
image: Visual Studio 2019
configuration: Release
environment:
  semantic_version: '0.1.0'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(semantic_version)
  file_version: '{version}'

install:
  - dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

deploy:
  - provider: NuGet
    api_key:
      secure: +xEtfNXyFQvh2BlB76UUiPveU35t5DuO7fPzh2LGK8H7Ty16Dfeqn80+eZ1s9/6C
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true
